Pipeline

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -17,17 +17,42 @@ jobs:
           role-to-assume: arn:aws:iam::972293797085:role/github-deploy-policy
           aws-region: us-west-1
 
-      - name: Print private IPs
+      - name: Fleet Health Checks
+        id: health
         run: |
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":["hostname -I"]}' \
-            --query 'Command.CommandId' --output text)
-
-          sleep 15
-
+            --parameters '{"commands":[
+              "hostname -I",
+              "docker --version 2>/dev/null  echo DOCKER NOT INSTALLED",
+              "aws --version 2>/dev/null  echo AWS CLI NOT INSTALLED",
+              "mysql --version 2>/dev/null || echo DOCKER NOT INSTALLED",
+              "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-east-1"
+              ]}' \
+            --query 'Command.CommandId' --output text \
+            --region us-west-1)
+          echo "cmd_id"=$"CMD_ID" >> $GITHUB_OUTPUT
+      
+      
+      - name: Show Results
+        run:   
+          sleep 20
           aws ssm list-command-invocations \
-            --command-id "$CMD_ID" --details \
-            --query "CommandInvocations[*].{Instance:InstanceId,IP:CommandPlugins[0].Output}" \
-            --output table
+            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --region us-west-1
+            --query "CommandInvocations[*].{Instance:InstanceId,Status,IP:CommandPlugins[0].Output}" \
+            --output text
+          
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-west-1
+            )
+
+          [ "$FAILED" -gt 0 ] && \
+          echo "::error::Health Check Failed on $FAILED instances" && \
+          exit 1
+
+          echo "ALL Instances Healthy ✅"
